sudo: required 
language: node_js
node_js:
    - 16
    
services: 
    - docker
before_install: 
    - docker build -t Ironicmoon/sample-docker-react -f Dockerfile.dev .
script:     
    - docker run -e CI=true Ironicmoon/sample-docker-react npm run test -- --coverage --watchAll=false